### ISSUE TITLE
Laufhelden fails to record position and track when GPS is off during App launch and when exercise has started.

### ISSUE THREAD

**Issue by CaptainKhan** [jdrescher2006/Laufhelden#10]
What it should be doing is position aquisition once GPS is turned on and even after Laufhelden has launched and is in the middle of an exercise.

Use case i would launch app, run downstairs and out of the house, but the GPS is off until i leave the house because there is no indoors GPS reception.

Ideally workout allows setting of standard starting point as well so position 0 is known even without GPS.

**Comment by jdrescher2006** [comment]
That is a tricky one.
The app relies strongly on enabled GPS with proper reception. This is because of Rena remnants.
I want to have track recording enabled if the record screen is shown, as it was in Meerun. Maybe I can get that into next release.
But what you want is a big thing. We need a GPS offline mode for the app so that we can do proper indoor workouts. That is in my plans but for later.

**Comment by CaptainKhan** [comment]
I am sure its a hard nut to crack but a worthwhile challenge! Even Jolla hasnt figured out how to set you GPS/Maps GPS 0 location and perform queries, map tiles etc, from that location instead of IP address location, last used location etc.

That would be fantastic. If you can figure something out making it more robust on interrupting GPS or starting GPS after workout has started that would be worth something! Flattr $$

**Comment by jdrescher2006** [comment]
Imagine you have a fixed (configurable) start position. And then start your next workout without GPS. You may get your GPS connection in 15 minutes. Everything between the first fixed position and the first GPS position is unknown. It could be 1km or 100km it is just not known.
I don't think this makes sense at all.
