### ISSUE TITLE
Localisation of Laufhelden - voice announcements question.

### ISSUE THREAD

**Issue by dikonov** [jdrescher2006/Laufhelden#104]
Am I right that Laufhelden must make own voice announcements to the runners? (I am not an app user myself.) What are the guidelines to translate these? Are they pre-recorded or synthesized on-the-spot?

I plan a Russian localization but the voice part may be a stumbling block. Russian voice synthesis engine currently available in SFOS (used by e.g. Billy Bass) is far behind the state-of-the-art level for the language and is barely intelligible. I can pre-record the messages, but I cannot provide a professional actor-level voice and need technical instructions on the list of messages, timing, sound file format, etc.

**Comment by jdrescher2006** [comment]
Hi dikonov,
yes the app uses prerecorded wav files. This is because I find the voice synthesis engines of horrible quality.
You can find all wav files in the folders /qml/audio, /qml/units, /qml/numbers. The filenames should speak for themselves. If you have for example the file "hr_toohigh_de_male.wav", that would be the words "heartrate too high". If you want to make a russian translation the file would be named "hr_toohigh_ru_male.wav" and be placed into the same folder.
I do the recording the following way. I use sound recorder on my smartphone and then I speak in all words needed. Everything is then in one large wav file. I open that file with audacity on my linux machine. First convert to mono. Then I mark each word and export it to a new wav file. Unfortunately there are quite a lot of files so this process will take some time. Keep in mind that there should not be a pause on the beginning and end of each file. Because if the app concatenates the files, there should be a smooth sentence created.

**Comment by dikonov** [comment]
I have made a set of Russian voice files matching the existing English and German ones. There are two versions: 
1. normal (some the messages are slightly longer than English). It is available as a pull request
2. higher tempo (artificially sped up to take the same amount of time or less than English). The tone is about the same, but the speech is faster.

**Comment by dikonov** [comment]
The first version of the Russian voice files has a quality problem. The files were recorded with different mikes, which gives the effect of several different voices saying words of each single phrase. Besides, the sound level is higher than English/German. I want to record a new improved version instead.

**Comment by jdrescher2006** [comment]
Hi dikonov, I listened to a few of your recordings and found them quite good. If you like you can record new ones, I also needed a few tries.

**Comment by jdrescher2006** [comment]
I think everything is OK here. Russian voice files working.
