### ISSUE TITLE
Single finger map drag to right causes screen swipe.

### ISSUE THREAD

**Issue by CaptainKhan** [jdrescher2006/Laufhelden#11]
Screen swipe should only activate when performed starting from left screen edge (Aquafish screen SFOS 2.1.0.11).

Or use two finger swipe to switch between screens (settings, map, and status metrics/summary)

**Comment by jdrescher2006** [comment]
This is the case only if the workout isn't started. Then you have the "pre record" page to the left. If the workout is started (this is when you want to drag the map), everything works OK.
I am not sure if a two finger swipe is intuitiv! I would rather think about reaching the "pre record" page differently so that swipe to right always drags the map.
Unfortunately I can't think of a better solution at the moment.

**Comment by jdrescher2006** [comment]
OK, today I was really annoyed by this. I am on holiday away from home and wanted to do a little run. So opened the map before starting workout to prepare where to go. And there it was, I could not scroll properly because of back navigation, really annoying.
You were right and I will fix this in next release.

**Comment by jdrescher2006** [comment]
Should be fixed with 0.9.5-6
