### ISSUE TITLE
Homepage doesn't show correct exercise, "walking" instead.

### ISSUE THREAD

**Issue by Nrde** [jdrescher2006/Laufhelden#72]
I have 4 exercises currently on my homepage, the oldest one being Running.
After a run I recorded a walk, and after that to runs.
Instead of showing:
Running
Running
Walking
Running

I get
Walking
Walking
Walking
Running

Additional problem is the icon in  beginning of each line. From top to bottom they are walk, run, walk, run. No logic which one is showing, unless they have different meaning than just visual identification.
![nayttokuva_20180402_001](https://user-images.githubusercontent.com/7312751/38238367-e106e470-3729-11e8-823d-f7411f18b5de.png)

**Comment by jdrescher2006** [comment]
The exercixes are sorted by date which is done correctly on your screenshot. First (bottom) comes 19.03. then 24.03. then 25.03. and last (most recent) comes 02.04.
Before you start the exercise in the app you have to pick the correct exercise type which is then saved to the GPX file. From the type in the GPX files the icons are generated.
Please make sure you use the latest version of the app because there was a bug regarding the saving of the exercise type.

**Comment by phylo-io** [comment]
I have selected running when I was running, the issue is the list shows I chose walking which is not true. Also the icon doesn't match the description even if I had chosen wrongly (which I didn't) when starting the exercise. Kävely = Walking, Juoksu = Running.

Summary, I chose "walking" once (second from bottom), all the other times I chose running, but the list doesn't reflect that and the icons are also wrong except the 2 bottom ones. (vs. what the text says after the icon.)

**Comment by jdrescher2006** [comment]
I guess there is a bug somewhere when the exercxise type is choosen and saved to the GPX file. I will check that.

**Comment by jdrescher2006** [comment]
One further question: do you have the autosave feature enabled (Automaatti tallennus)?

**Comment by Nrde** [comment]
Yes, autosave is on.

**Comment by jdrescher2006** [comment]
Could you check if the problem still exists with the new version v1.1.0? If you still have that problem, please exactly describe the steps to reproduce it.

**Comment by Nrde** [comment]
I have made one exercise after updating to 1.0.1 and it seemed to be ok. Although after I enabled and disabled autonaming it started to work with the previous version too. But if you made some fixes to this, I'm sure it's ok now. I will re-open this with additional info if I have it again. Can be closed.
