### ISSUE TITLE
Misleading Cancel button at the save workout screen

### ISSUE THREAD

**Issue by martonmiklos** [jdrescher2006/Laufhelden#87]
I think the "Cancel button" on the save screen is a bit misleading: user could think that this is the way to get back to the workout's main screen (to continue the workout recording maybe). But if (s)he click to that the recorded data will be lost (and the user will get back to the main screen). 

I think it either would be better to call it Delete just like the Meerun called or add an extra "alert dialog" before getting back to the main screen.

**Comment by jdrescher2006** [comment]
Yeah you are right about this. I don't know what the best way is. A dialog with three buttons would be an other option: "Save, Cancel, Exit". The dialog is already in a separate QML file: SaveDialog.qml. Maybe the three buttons could be arranged one below the other. What do you think?

**Comment by martonmiklos** [comment]
Well I think we should follow the SFOS UI paradigm where the white(ish) circles on the top left and right corners are used for navigation between the pages. In this case the Cancel button text is ok, but the user should be redirected to the Workout view. 

To implement the quit without saving feature I would propose to add an item to the pulldown in the Workout view.

**Comment by jdrescher2006** [comment]
I don't think that's a good way. There are already too many menu options on the record page. I have to think about this...

**Comment by martonmiklos** [comment]
Well I agree. 
What if we would simply add a button to the save page with title something like "Drop recorded data" or similar?

Then we would handle the pagestack navigation in the "SFOS way", and would still provide an option to quit without saving?

**Comment by jdrescher2006** [comment]
That's a very good idea. I will include that in the next release.

**Comment by jdrescher2006** [comment]
I am still struggling with this issue.
If a user wants to save the workout, he needs to write name and description. This may last some time (e.g. some seconds to minutes). During this time, the workout is still running which leads to the workout beeing longer than it is supposed to.
I don't know how to fix this at the moment. I can not simply end the workout on opening the save dialog, because the user may want to cancel this action (with the new cancel option) and then the workout needs to resume without pause or anything.
Maybe I could end the workout if the user starts to write on the name or description field and then also disable the cancel button.

**Comment by Nrde** [comment]
Take a snapshot / save a "draft" when the dialog opens. Then either remove it on cancel or proceed with save (or mark it as "final"). Sorry I haven't looked how the save works currently so maybe this is not feasible.

**Comment by jdrescher2006** [comment]
I renamed the Cancel option. Should be OK now.
